---
- name: Install required system packages.
  apt:
    name:
      - gpg-agent
      - apt-transport-https
    state: present
    cache_valid_time: "{{ apt_cache_valid_time | default(3600) }}"

- name: Add Raspotify GPG key.
  apt_key:
    url: https://dtcooper.github.io/raspotify/key.asc
    state: present

- name: Add Raspotify apt repository.
  apt_repository:
    repo: deb https://dtcooper.github.io/raspotify raspotify main
    state: present
  register: raspotify_repo_result

- name: Install Raspotify package.
  apt:
    name: raspotify
    update_cache: "{{ raspotify_repo_result.changed }}"
