---
- name: Install required system packages.
  apt:
    name:
      - gpg-agent
      - apt-transport-https
    state: present
    cache_valid_time: "{{ apt_cache_valid_time | default(3600) }}"

- name: Add Raspotify GPG key.
  apt_key:
    url: https://dtcooper.github.io/raspotify/key.asc
    state: present

- name: Add Raspotify apt repository.
  apt_repository:
    repo: deb https://dtcooper.github.io/raspotify raspotify main
    state: present
  register: raspotify_repo_result

- name: Install Raspotify package.
  apt:
    name: "{{ 'raspotify:armhf' if ansible_machine == 'aarch64' else 'raspotify' }}"
    update_cache: true
  register: apt_install_result

- name: Update configuration file.
  template:
    src: templates/raspotify.j2
    dest: /etc/default/raspotify
    owner: root
    group: root
    mode: "0644"
  notify: Restart the raspotify service.

- name: Enable the raspotify service.
  systemd:
    name: raspotify.service
    state: started
    enabled: true
  when: raspotify_service

- name: Disable the raspotify service.
  systemd:
    name: raspotify.service
    state: started
    enabled: true
  when: not raspotify_service